const actionTypes = {
    personActions:{
        GET_PERSON_START:"GET_PERSON_START",
        GET_PERSON_SUCCESS:"GET_PERSON_SUCCESS",
        GET_PERSON_FAIL:"GET_PERSON_FAIL",

        DELETE_PERSON_START:" DELETE_PERSON_START",
        DELETE_PERSON_SUCCESS:" DELETE_PERSON_SUCCESS",
        DELETE_PERSON_FAIL:" DELETE_PERSON_FAIL",

        ADD_PERSON_START:" ADD_PERSON_START",
        ADD_PERSON_SUCCESS:" ADD_PERSON_SUCCESS",
        ADD_PERSON_FAIL:" ADD_PERSON_FAIL",

        EDIT_PERSON_START:" EDIT_PERSON_START",
        EDIT_PERSON_SUCCESS:" EDIT_PERSON_SUCCESS",
        EDIT_PERSON_FAIL:" EDIT_PERSON_FAIL",

    },
    categoryActions:{
        GET_CATEGORY_START:"GET_CATEGORY_START",
        GET_CATEGORY_SUCCESS:"GET_CATEGORY_SUCCESS",
        GET_CATEGORY_FAIL:"GET_CATEGORY_FAIL",

        DELETE_CATEGORY_START:" DELETE_CATEGORY_START",
        DELETE_CATEGORY_SUCCESS:" DELETE_CATEGORY_SUCCESS",
        DELETE_CATEGORY_FAIL:" DELETE_CATEGORY_FAIL",

        ADD_CATEGORY_START:" ADD_CATEGORY_START",
        ADD_CATEGORY_SUCCESS:" ADD_CATEGORY_SUCCESS",
        ADD_CATEGORY_FAIL:" ADD_CATEGORY_FAIL",

        EDIT_CATEGORY_START:" EDIT_CATEGORY_START",
        EDIT_CATEGORY_SUCCESS:" EDIT_CATEGORY_SUCCESS",
        EDIT_CATEGORY_FAIL:" EDIT_CATEGORY_FAIL",
    },
};

export default actionTypes